var hierarchy =
[
    [ "edit_atlas::presentation::AppearancePalette", "structedit__atlas_1_1presentation_1_1AppearancePalette.html", null ],
    [ "edit_atlas::presentation::ApplicationTypography", "structedit__atlas_1_1presentation_1_1ApplicationTypography.html", null ],
    [ "edit_atlas::core::Comment", "structedit__atlas_1_1core_1_1Comment.html", null ],
    [ "edit_atlas::media::DecodedVideoFrame", "structedit__atlas_1_1media_1_1DecodedVideoFrame.html", null ],
    [ "edit_atlas::core::Diagnostic", "structedit__atlas_1_1core_1_1Diagnostic.html", null ],
    [ "edit_atlas::support::DiagnosticEnvironment", "structedit__atlas_1_1support_1_1DiagnosticEnvironment.html", null ],
    [ "edit_atlas::core::EditEvent", "structedit__atlas_1_1core_1_1EditEvent.html", null ],
    [ "edit_atlas::core::ExportArtifact", "structedit__atlas_1_1core_1_1ExportArtifact.html", null ],
    [ "edit_atlas::core::Exporter", "classedit__atlas_1_1core_1_1Exporter.html", [
      [ "edit_atlas::formats::xlsx::XlsxExporter", "classedit__atlas_1_1formats_1_1xlsx_1_1XlsxExporter.html", null ]
    ] ],
    [ "edit_atlas::core::ExportRequest", "structedit__atlas_1_1core_1_1ExportRequest.html", null ],
    [ "edit_atlas::core::ExportResult", "structedit__atlas_1_1core_1_1ExportResult.html", null ],
    [ "edit_atlas::core::FormatDescriptor", "structedit__atlas_1_1core_1_1FormatDescriptor.html", null ],
    [ "edit_atlas::core::FormatRegistry", "classedit__atlas_1_1core_1_1FormatRegistry.html", null ],
    [ "edit_atlas::core::FrameRate", "classedit__atlas_1_1core_1_1FrameRate.html", null ],
    [ "edit_atlas::core::Importer", "classedit__atlas_1_1core_1_1Importer.html", [
      [ "edit_atlas::formats::cmx3600::Cmx3600Importer", "classedit__atlas_1_1formats_1_1cmx3600_1_1Cmx3600Importer.html", null ]
    ] ],
    [ "edit_atlas::core::ImportRequest", "structedit__atlas_1_1core_1_1ImportRequest.html", null ],
    [ "edit_atlas::core::ImportResult", "structedit__atlas_1_1core_1_1ImportResult.html", null ],
    [ "edit_atlas::support::LoggingInitializationFailure", "structedit__atlas_1_1support_1_1LoggingInitializationFailure.html", null ],
    [ "edit_atlas::support::LoggingOptions", "structedit__atlas_1_1support_1_1LoggingOptions.html", null ],
    [ "edit_atlas::media::MediaMetadataEntry", "structedit__atlas_1_1media_1_1MediaMetadataEntry.html", null ],
    [ "edit_atlas::media::MediaStreamInfo", "structedit__atlas_1_1media_1_1MediaStreamInfo.html", null ],
    [ "edit_atlas::core::MetadataEntry", "structedit__atlas_1_1core_1_1MetadataEntry.html", null ],
    [ "QAbstractListModel", null, [
      [ "edit_atlas::presentation::TimelineEventProjectionModel", "classedit__atlas_1_1presentation_1_1TimelineEventProjectionModel.html", null ],
      [ "edit_atlas::presentation::TimelineFilterModel", "classedit__atlas_1_1presentation_1_1TimelineFilterModel.html", null ],
      [ "edit_atlas::presentation::TimelineTemplateModel", "classedit__atlas_1_1presentation_1_1TimelineTemplateModel.html", null ]
    ] ],
    [ "QAbstractTableModel", null, [
      [ "edit_atlas::presentation::DiagnosticModel", "classedit__atlas_1_1presentation_1_1DiagnosticModel.html", null ],
      [ "edit_atlas::presentation::TimelineEventModel", "classedit__atlas_1_1presentation_1_1TimelineEventModel.html", null ]
    ] ],
    [ "QObject", null, [
      [ "edit_atlas::presentation::AppearanceController", "classedit__atlas_1_1presentation_1_1AppearanceController.html", null ],
      [ "edit_atlas::presentation::SupportBundleViewModel", "classedit__atlas_1_1presentation_1_1SupportBundleViewModel.html", null ],
      [ "edit_atlas::presentation::SupportBundleWorkflow", "classedit__atlas_1_1presentation_1_1SupportBundleWorkflow.html", null ],
      [ "edit_atlas::presentation::TimelineDocumentViewModel", "classedit__atlas_1_1presentation_1_1TimelineDocumentViewModel.html", null ],
      [ "edit_atlas::presentation::TimelineDocumentWorkflow", "classedit__atlas_1_1presentation_1_1TimelineDocumentWorkflow.html", null ],
      [ "edit_atlas::presentation::TimelineTemplateViewModel", "classedit__atlas_1_1presentation_1_1TimelineTemplateViewModel.html", null ]
    ] ],
    [ "edit_atlas::media::Rational", "structedit__atlas_1_1media_1_1Rational.html", null ],
    [ "edit_atlas::core::RgbImage", "structedit__atlas_1_1core_1_1RgbImage.html", null ],
    [ "edit_atlas::core::SourceLineProvenance", "structedit__atlas_1_1core_1_1SourceLineProvenance.html", null ],
    [ "edit_atlas::core::SourceLocation", "structedit__atlas_1_1core_1_1SourceLocation.html", null ],
    [ "edit_atlas::support::SupportBundleFailure", "structedit__atlas_1_1support_1_1SupportBundleFailure.html", null ],
    [ "edit_atlas::support::SupportBundleReceipt", "structedit__atlas_1_1support_1_1SupportBundleReceipt.html", null ],
    [ "edit_atlas::support::SupportBundleRequest", "structedit__atlas_1_1support_1_1SupportBundleRequest.html", null ],
    [ "edit_atlas::core::Timecode", "classedit__atlas_1_1core_1_1Timecode.html", null ],
    [ "edit_atlas::core::TimecodeRange", "classedit__atlas_1_1core_1_1TimecodeRange.html", null ],
    [ "edit_atlas::core::TimelineDocument", "structedit__atlas_1_1core_1_1TimelineDocument.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportFailure", "structedit__atlas_1_1services_1_1TimelineDocumentExportFailure.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportReceipt", "structedit__atlas_1_1services_1_1TimelineDocumentExportReceipt.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportRequest", "structedit__atlas_1_1services_1_1TimelineDocumentExportRequest.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportService", "classedit__atlas_1_1services_1_1TimelineDocumentExportService.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportFailure", "structedit__atlas_1_1services_1_1TimelineDocumentImportFailure.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportReceipt", "structedit__atlas_1_1services_1_1TimelineDocumentImportReceipt.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportRequest", "structedit__atlas_1_1services_1_1TimelineDocumentImportRequest.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportService", "classedit__atlas_1_1services_1_1TimelineDocumentImportService.html", null ],
    [ "edit_atlas::core::TimelineDocumentPipeline", "classedit__atlas_1_1core_1_1TimelineDocumentPipeline.html", null ],
    [ "edit_atlas::services::TimelineDurationFilterCondition", "structedit__atlas_1_1services_1_1TimelineDurationFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineEditTypeFilterCondition", "structedit__atlas_1_1services_1_1TimelineEditTypeFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineEventFrame", "structedit__atlas_1_1services_1_1TimelineEventFrame.html", null ],
    [ "edit_atlas::core::TimelineEventImage", "structedit__atlas_1_1core_1_1TimelineEventImage.html", null ],
    [ "edit_atlas::presentation::TimelineExportRequest", "structedit__atlas_1_1presentation_1_1TimelineExportRequest.html", null ],
    [ "edit_atlas::services::TimelineFilterError", "structedit__atlas_1_1services_1_1TimelineFilterError.html", null ],
    [ "edit_atlas::services::TimelineFilterQuery", "structedit__atlas_1_1services_1_1TimelineFilterQuery.html", null ],
    [ "edit_atlas::services::TimelineFrameExtractionFailure", "structedit__atlas_1_1services_1_1TimelineFrameExtractionFailure.html", null ],
    [ "edit_atlas::services::TimelineFrameExtractionOptions", "structedit__atlas_1_1services_1_1TimelineFrameExtractionOptions.html", null ],
    [ "edit_atlas::services::TimelineFrameExtractionProgress", "structedit__atlas_1_1services_1_1TimelineFrameExtractionProgress.html", null ],
    [ "edit_atlas::services::TimelineFrameExtractionReceipt", "structedit__atlas_1_1services_1_1TimelineFrameExtractionReceipt.html", null ],
    [ "edit_atlas::services::TimelineFrameExtractionService", "classedit__atlas_1_1services_1_1TimelineFrameExtractionService.html", null ],
    [ "edit_atlas::services::TimelineRenderedVideoExportFailure", "structedit__atlas_1_1services_1_1TimelineRenderedVideoExportFailure.html", null ],
    [ "edit_atlas::services::TimelineRenderedVideoExportReceipt", "structedit__atlas_1_1services_1_1TimelineRenderedVideoExportReceipt.html", null ],
    [ "edit_atlas::services::TimelineRenderedVideoExportRequest", "structedit__atlas_1_1services_1_1TimelineRenderedVideoExportRequest.html", null ],
    [ "edit_atlas::services::TimelineRenderedVideoExportService", "classedit__atlas_1_1services_1_1TimelineRenderedVideoExportService.html", null ],
    [ "edit_atlas::services::TimelineTemplate", "structedit__atlas_1_1services_1_1TimelineTemplate.html", null ],
    [ "edit_atlas::services::TimelineTemplateFailure", "structedit__atlas_1_1services_1_1TimelineTemplateFailure.html", null ],
    [ "edit_atlas::services::TimelineTemplateLoadDiagnostic", "structedit__atlas_1_1services_1_1TimelineTemplateLoadDiagnostic.html", null ],
    [ "edit_atlas::services::TimelineTemplateService", "classedit__atlas_1_1services_1_1TimelineTemplateService.html", null ],
    [ "edit_atlas::services::TimelineTextFilterCondition", "structedit__atlas_1_1services_1_1TimelineTextFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineTimecodeFilterCondition", "structedit__atlas_1_1services_1_1TimelineTimecodeFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineTrackKindFilterCondition", "structedit__atlas_1_1services_1_1TimelineTrackKindFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineVideoInspectionFailure", "structedit__atlas_1_1services_1_1TimelineVideoInspectionFailure.html", null ],
    [ "edit_atlas::services::TimelineVideoInspectionReceipt", "structedit__atlas_1_1services_1_1TimelineVideoInspectionReceipt.html", null ],
    [ "edit_atlas::services::TimelineVideoInspectionService", "classedit__atlas_1_1services_1_1TimelineVideoInspectionService.html", null ],
    [ "edit_atlas::services::TimelineVideoMapping", "structedit__atlas_1_1services_1_1TimelineVideoMapping.html", null ],
    [ "edit_atlas::services::TimelineVideoValidationFailure", "structedit__atlas_1_1services_1_1TimelineVideoValidationFailure.html", null ],
    [ "edit_atlas::core::Track", "structedit__atlas_1_1core_1_1Track.html", null ],
    [ "edit_atlas::core::Transition", "structedit__atlas_1_1core_1_1Transition.html", null ],
    [ "edit_atlas::media::VideoBackendInformation", "structedit__atlas_1_1media_1_1VideoBackendInformation.html", null ],
    [ "edit_atlas::media::VideoDecoder", "classedit__atlas_1_1media_1_1VideoDecoder.html", null ],
    [ "edit_atlas::media::VideoDecoderFailure", "structedit__atlas_1_1media_1_1VideoDecoderFailure.html", null ],
    [ "edit_atlas::media::VideoFrameOutputOptions", "structedit__atlas_1_1media_1_1VideoFrameOutputOptions.html", null ],
    [ "edit_atlas::media::VideoFrameSizeLimit", "structedit__atlas_1_1media_1_1VideoFrameSizeLimit.html", null ],
    [ "edit_atlas::media::VideoMediaInfo", "structedit__atlas_1_1media_1_1VideoMediaInfo.html", null ]
];