"""Runner-independent contract for semantic desktop automation."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, Sequence


class DesktopElement(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def role_name(self) -> str: ...


class DesktopSession(Protocol):
    def activate(self, identifier: str) -> None: ...

    def activate_named(
        self, names: Sequence[str], *, within: str | None = None
    ) -> None: ...

    def capture_artifacts(self, stem: str) -> None: ...

    def close(self) -> None: ...

    def element(self, identifier: str, *, showing: bool = True) -> DesktopElement: ...

    def element_name(self, identifier: str, *, showing: bool = True) -> str: ...

    def has_element(self, identifier: str, *, showing: bool = True) -> bool: ...

    def is_checked(self, identifier: str) -> bool: ...

    def is_sensitive(self, identifier: str) -> bool: ...

    def list_items(self, identifier: str) -> list[str]: ...

    def is_list_item_checked(self, identifier: str, name: str) -> bool: ...

    def open_file_dialog(self, dialog_identifier: str, path: Path) -> None: ...

    def activate_menu_action(
        self, menu_identifier: str, action_identifier: str
    ) -> None: ...

    def select_option(self, identifier: str, option: str) -> None: ...

    def select_list_item(self, identifier: str, name: str) -> None: ...

    def selected_option(self, identifier: str) -> str: ...

    def set_checked(self, identifier: str, checked: bool) -> None: ...

    def set_list_item_checked(
        self, identifier: str, name: str, checked: bool
    ) -> None: ...

    def set_text(self, identifier: str, value: str) -> None: ...

    def text(self, identifier: str, *, showing: bool = True) -> str: ...

    def text_content(self, identifier: str) -> list[str]: ...

    def visible_text(self, identifier: str) -> list[str]: ...

    def wait_absent(self, identifier: str) -> None: ...

    def wait_name_contains(self, identifier: str, expected: str) -> str: ...

    def wait_list_items(
        self, identifier: str, expected: Sequence[str]
    ) -> list[str]: ...

    def wait_selected_option(self, identifier: str, expected: str) -> str: ...

    def wait_sensitive(self, identifier: str, expected: bool) -> bool: ...

    def wait_text_contains(self, identifier: str, expected: str) -> str: ...

    def wait_text_nonempty(self, identifier: str) -> str: ...
