var hierarchy =
[
    [ "edit_atlas::core::Comment", "structedit__atlas_1_1core_1_1Comment.html", null ],
    [ "edit_atlas::core::Diagnostic", "structedit__atlas_1_1core_1_1Diagnostic.html", null ],
    [ "edit_atlas::support::DiagnosticEnvironment", "structedit__atlas_1_1support_1_1DiagnosticEnvironment.html", null ],
    [ "edit_atlas::core::EditEvent", "structedit__atlas_1_1core_1_1EditEvent.html", null ],
    [ "edit_atlas::core::ExportArtifact", "structedit__atlas_1_1core_1_1ExportArtifact.html", null ],
    [ "edit_atlas::core::Exporter", "classedit__atlas_1_1core_1_1Exporter.html", [
      [ "edit_atlas::formats::xlsx::XlsxExporter", "classedit__atlas_1_1formats_1_1xlsx_1_1XlsxExporter.html", null ]
    ] ],
    [ "edit_atlas::core::ExportRequest", "structedit__atlas_1_1core_1_1ExportRequest.html", null ],
    [ "edit_atlas::core::ExportResult", "structedit__atlas_1_1core_1_1ExportResult.html", null ],
    [ "edit_atlas::core::FormatDescriptor", "structedit__atlas_1_1core_1_1FormatDescriptor.html", null ],
    [ "edit_atlas::core::FormatRegistry", "classedit__atlas_1_1core_1_1FormatRegistry.html", null ],
    [ "edit_atlas::core::FrameRate", "classedit__atlas_1_1core_1_1FrameRate.html", null ],
    [ "edit_atlas::core::Importer", "classedit__atlas_1_1core_1_1Importer.html", [
      [ "edit_atlas::formats::cmx3600::Cmx3600Importer", "classedit__atlas_1_1formats_1_1cmx3600_1_1Cmx3600Importer.html", null ]
    ] ],
    [ "edit_atlas::core::ImportRequest", "structedit__atlas_1_1core_1_1ImportRequest.html", null ],
    [ "edit_atlas::core::ImportResult", "structedit__atlas_1_1core_1_1ImportResult.html", null ],
    [ "edit_atlas::support::LoggingInitializationFailure", "structedit__atlas_1_1support_1_1LoggingInitializationFailure.html", null ],
    [ "edit_atlas::support::LoggingOptions", "structedit__atlas_1_1support_1_1LoggingOptions.html", null ],
    [ "edit_atlas::core::MetadataEntry", "structedit__atlas_1_1core_1_1MetadataEntry.html", null ],
    [ "edit_atlas::core::SourceLineProvenance", "structedit__atlas_1_1core_1_1SourceLineProvenance.html", null ],
    [ "edit_atlas::core::SourceLocation", "structedit__atlas_1_1core_1_1SourceLocation.html", null ],
    [ "edit_atlas::support::SupportBundleFailure", "structedit__atlas_1_1support_1_1SupportBundleFailure.html", null ],
    [ "edit_atlas::support::SupportBundleReceipt", "structedit__atlas_1_1support_1_1SupportBundleReceipt.html", null ],
    [ "edit_atlas::support::SupportBundleRequest", "structedit__atlas_1_1support_1_1SupportBundleRequest.html", null ],
    [ "edit_atlas::core::Timecode", "classedit__atlas_1_1core_1_1Timecode.html", null ],
    [ "edit_atlas::core::TimecodeRange", "classedit__atlas_1_1core_1_1TimecodeRange.html", null ],
    [ "edit_atlas::core::TimelineDocument", "structedit__atlas_1_1core_1_1TimelineDocument.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportFailure", "structedit__atlas_1_1services_1_1TimelineDocumentExportFailure.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportReceipt", "structedit__atlas_1_1services_1_1TimelineDocumentExportReceipt.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportRequest", "structedit__atlas_1_1services_1_1TimelineDocumentExportRequest.html", null ],
    [ "edit_atlas::services::TimelineDocumentExportService", "classedit__atlas_1_1services_1_1TimelineDocumentExportService.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportFailure", "structedit__atlas_1_1services_1_1TimelineDocumentImportFailure.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportReceipt", "structedit__atlas_1_1services_1_1TimelineDocumentImportReceipt.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportRequest", "structedit__atlas_1_1services_1_1TimelineDocumentImportRequest.html", null ],
    [ "edit_atlas::services::TimelineDocumentImportService", "classedit__atlas_1_1services_1_1TimelineDocumentImportService.html", null ],
    [ "edit_atlas::core::TimelineDocumentPipeline", "classedit__atlas_1_1core_1_1TimelineDocumentPipeline.html", null ],
    [ "edit_atlas::services::TimelineDurationFilterCondition", "structedit__atlas_1_1services_1_1TimelineDurationFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineEditTypeFilterCondition", "structedit__atlas_1_1services_1_1TimelineEditTypeFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineFilterError", "structedit__atlas_1_1services_1_1TimelineFilterError.html", null ],
    [ "edit_atlas::services::TimelineFilterQuery", "structedit__atlas_1_1services_1_1TimelineFilterQuery.html", null ],
    [ "edit_atlas::services::TimelineTemplate", "structedit__atlas_1_1services_1_1TimelineTemplate.html", null ],
    [ "edit_atlas::services::TimelineTemplateFailure", "structedit__atlas_1_1services_1_1TimelineTemplateFailure.html", null ],
    [ "edit_atlas::services::TimelineTemplateLoadDiagnostic", "structedit__atlas_1_1services_1_1TimelineTemplateLoadDiagnostic.html", null ],
    [ "edit_atlas::services::TimelineTemplateService", "classedit__atlas_1_1services_1_1TimelineTemplateService.html", null ],
    [ "edit_atlas::services::TimelineTextFilterCondition", "structedit__atlas_1_1services_1_1TimelineTextFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineTimecodeFilterCondition", "structedit__atlas_1_1services_1_1TimelineTimecodeFilterCondition.html", null ],
    [ "edit_atlas::services::TimelineTrackKindFilterCondition", "structedit__atlas_1_1services_1_1TimelineTrackKindFilterCondition.html", null ],
    [ "edit_atlas::core::Track", "structedit__atlas_1_1core_1_1Track.html", null ],
    [ "edit_atlas::core::Transition", "structedit__atlas_1_1core_1_1Transition.html", null ]
];